crudclass/crud/urls.py
# -*- coding: utf-8 -*-
"""!
* @software Aprendiendo Django 1.11
* @version 1.0 - 2018
* @author Ing. Angelo D. Osorio U.
* @license Fundación CENDITEL (2018)
* @file crud/urls.py
* @brief Rutas del módulo crud
"""

# Importa la función url desde Django
from django.conf.urls import url

# Importa las vistas creadas en crud/views.py
from .views import (
    CourseList,
    CourseDetail,
    CourseCreation,
    CourseUpdate,
    CourseDelete
)

urlpatterns = [
    # Lista los cursos creados
    url(r'^$', CourseList.as_view(), name='list'),
    
    # Edita el curso cuyo id sea igual al solicitado en la url
    url(r'^(?P<pk>\d+)$', CourseDetail.as_view(), name='detail'),

    # Envía al formulario para crear un nuevo curso
    url(r'^nuevo$', CourseCreation.as_view(), name='new'),
    
    # Edita un curso que se haya guardado con anterioridad
    url(r'^editar/(?P<pk>\d+)$', CourseUpdate.as_view(), name='edit'),

    # Solicita eliminar un curso
    url(r'^borrar/(?P<pk>\d+)$', CourseDelete.as_view(), name='delete'),
]

crudclass/crudclass/urls.py
# -*- coding: utf-8 -*-
"""crudclass URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # URLS de la aplicación crud
    url(r'^crud/', include('crud.urls', namespace='crud')),
]

crudclass/crud/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=140)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    #picture = models.ImageField(upload_to='media/courses/pictures')

crudclass/crud/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)

from django.core.urlresolvers import reverse_lazy
from .models import Course

# Listar cursos
class CourseList(ListView):
    model = Course

# Detalles del curso
class CourseDetail(DetailView):
    model = Course

# Crear un curso
class CourseCreation(CreateView):
    model = Course
    success_url = reverse_lazy('crud:list')
    fields = ['name', 'start_date', 'end_date']

# Actualizar un curso
class CourseUpdate(UpdateView):
    model = Course
    success_url = reverse_lazy('crud:list')
    fields = ['name', 'start_date', 'end_date']

# Eliminar un curso
class CourseDelete(DeleteView):
    model = Course
    success_url = reverse_lazy('crud:list')

crudclass/crud/templates/crud/course_confirm_delete.html
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el curso "<b>{{ object.name }}</b>"?
    <input type="submit" value="Eliminar" />
</form>

crudclass/crud/templates/crud/course_detail.html
<h1>{{ course.name }}</h1>
<p>Fecha de inicio: <i>{{ course.start_date }}</i></p>
<p>Fecha de fin: <i>{{ course.end_date }}</i></p>
<p>
    <a href="{% url "crud:list" %}">Regresar</a>
</p>

crudclass/crud/templates/crud/course_form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

crudclass/crud/templates/crud/course_list.html
<h1>Cursos de Platzi</h1>

<p>
    <a href="{% url "crud:new" %}">Agregar curso</a>
</p>

<ul>
    {% for course in object_list %}
        <li>
            <p>{{ course.name }}</p>
            <p>
                <a href="{% url "crud:detail" course.id %}">Ver</a> | 
                <a href="{% url "crud:edit" course.id %}">Editar</a> | 
                <a href="{% url "crud:delete" course.id %}">Borrar</a> 
            </p>
        </li>
    {% endfor %}
</ul>